# Generated by Django 5.0.6 on 2024-05-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_picsture_contact_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='picsture',
            new_name='picture',
        ),
    ]
